// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.2
// source: proto/precrux/precrux.proto

package precrux

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PrecruxRequest is the request for precrux.
type PrecruxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrecruxRequest) Reset() {
	*x = PrecruxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_precrux_precrux_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecruxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecruxRequest) ProtoMessage() {}

func (x *PrecruxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_precrux_precrux_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecruxRequest.ProtoReflect.Descriptor instead.
func (*PrecruxRequest) Descriptor() ([]byte, []int) {
	return file_proto_precrux_precrux_proto_rawDescGZIP(), []int{0}
}

func (x *PrecruxRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PrecruxResponse is the response for precrux.
type PrecruxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrecruxResponse) Reset() {
	*x = PrecruxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_precrux_precrux_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecruxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecruxResponse) ProtoMessage() {}

func (x *PrecruxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_precrux_precrux_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecruxResponse.ProtoReflect.Descriptor instead.
func (*PrecruxResponse) Descriptor() ([]byte, []int) {
	return file_proto_precrux_precrux_proto_rawDescGZIP(), []int{1}
}

func (x *PrecruxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_precrux_precrux_proto protoreflect.FileDescriptor

var file_proto_precrux_precrux_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2f,
	0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63,
	0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78,
	0x22, 0x2a, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0f,
	0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x62, 0x0a, 0x07, 0x50, 0x72, 0x65,
	0x63, 0x72, 0x75, 0x78, 0x12, 0x57, 0x0a, 0x0c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x72, 0x65,
	0x63, 0x72, 0x75, 0x78, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65, 0x65,
	0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79,
	0x76, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x50, 0x72, 0x65, 0x63,
	0x72, 0x75, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x69, 0x6c,
	0x6c, 0x79, 0x76, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_precrux_precrux_proto_rawDescOnce sync.Once
	file_proto_precrux_precrux_proto_rawDescData = file_proto_precrux_precrux_proto_rawDesc
)

func file_proto_precrux_precrux_proto_rawDescGZIP() []byte {
	file_proto_precrux_precrux_proto_rawDescOnce.Do(func() {
		file_proto_precrux_precrux_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_precrux_precrux_proto_rawDescData)
	})
	return file_proto_precrux_precrux_proto_rawDescData
}

var file_proto_precrux_precrux_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_precrux_precrux_proto_goTypes = []interface{}{
	(*PrecruxRequest)(nil),  // 0: chillyvee.precrux.PrecruxRequest
	(*PrecruxResponse)(nil), // 1: chillyvee.precrux.PrecruxResponse
}
var file_proto_precrux_precrux_proto_depIdxs = []int32{
	0, // 0: chillyvee.precrux.Precrux.UnaryPrecrux:input_type -> chillyvee.precrux.PrecruxRequest
	1, // 1: chillyvee.precrux.Precrux.UnaryPrecrux:output_type -> chillyvee.precrux.PrecruxResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_precrux_precrux_proto_init() }
func file_proto_precrux_precrux_proto_init() {
	if File_proto_precrux_precrux_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_precrux_precrux_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecruxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_precrux_precrux_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecruxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_precrux_precrux_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_precrux_precrux_proto_goTypes,
		DependencyIndexes: file_proto_precrux_precrux_proto_depIdxs,
		MessageInfos:      file_proto_precrux_precrux_proto_msgTypes,
	}.Build()
	File_proto_precrux_precrux_proto = out.File
	file_proto_precrux_precrux_proto_rawDesc = nil
	file_proto_precrux_precrux_proto_goTypes = nil
	file_proto_precrux_precrux_proto_depIdxs = nil
}
