// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.21.2
// source: proto/precrux/precrux.proto

package precrux

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// PrecruxRequest is the request for precrux.
type PrecruxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrecruxRequest) Reset() {
	*x = PrecruxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_precrux_precrux_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecruxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecruxRequest) ProtoMessage() {}

func (x *PrecruxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_precrux_precrux_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecruxRequest.ProtoReflect.Descriptor instead.
func (*PrecruxRequest) Descriptor() ([]byte, []int) {
	return file_proto_precrux_precrux_proto_rawDescGZIP(), []int{0}
}

func (x *PrecruxRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PrecruxResponse is the response for precrux.
type PrecruxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrecruxResponse) Reset() {
	*x = PrecruxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_precrux_precrux_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecruxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecruxResponse) ProtoMessage() {}

func (x *PrecruxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_precrux_precrux_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecruxResponse.ProtoReflect.Descriptor instead.
func (*PrecruxResponse) Descriptor() ([]byte, []int) {
	return file_proto_precrux_precrux_proto_rawDescGZIP(), []int{1}
}

func (x *PrecruxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PrecruxWriteFileRequest is the request for precrux.
type PrecruxWriteFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filepath  string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Perm      uint32 `protobuf:"varint,3,opt,name=perm,proto3" json:"perm,omitempty"`
	Overwrite bool   `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
}

func (x *PrecruxWriteFileRequest) Reset() {
	*x = PrecruxWriteFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_precrux_precrux_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecruxWriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecruxWriteFileRequest) ProtoMessage() {}

func (x *PrecruxWriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_precrux_precrux_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecruxWriteFileRequest.ProtoReflect.Descriptor instead.
func (*PrecruxWriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_precrux_precrux_proto_rawDescGZIP(), []int{2}
}

func (x *PrecruxWriteFileRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *PrecruxWriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PrecruxWriteFileRequest) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

func (x *PrecruxWriteFileRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// PrecruxWriteFileResponse is the response for precrux.
type PrecruxWriteFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrecruxWriteFileResponse) Reset() {
	*x = PrecruxWriteFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_precrux_precrux_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecruxWriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecruxWriteFileResponse) ProtoMessage() {}

func (x *PrecruxWriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_precrux_precrux_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecruxWriteFileResponse.ProtoReflect.Descriptor instead.
func (*PrecruxWriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_precrux_precrux_proto_rawDescGZIP(), []int{3}
}

func (x *PrecruxWriteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrecruxWriteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_precrux_precrux_proto protoreflect.FileDescriptor

var file_proto_precrux_precrux_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2f,
	0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63,
	0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78,
	0x22, 0x2a, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0f,
	0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7b, 0x0a, 0x17, 0x50, 0x72, 0x65,
	0x63, 0x72, 0x75, 0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x65, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x76, 0x65, 0x72,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f, 0x76, 0x65,
	0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x22, 0x4e, 0x0a, 0x18, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75,
	0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xca, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x63, 0x72,
	0x75, 0x78, 0x12, 0x57, 0x0a, 0x0c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x72, 0x65, 0x63, 0x72,
	0x75, 0x78, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65, 0x65, 0x2e, 0x70,
	0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65,
	0x65, 0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x09, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2a, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x6c,
	0x79, 0x76, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x50, 0x72, 0x65,
	0x63, 0x72, 0x75, 0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65, 0x65,
	0x2e, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x50, 0x72, 0x65, 0x63, 0x72, 0x75, 0x78,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79, 0x76, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x63,
	0x72, 0x75, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x63, 0x72, 0x75,
	0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_precrux_precrux_proto_rawDescOnce sync.Once
	file_proto_precrux_precrux_proto_rawDescData = file_proto_precrux_precrux_proto_rawDesc
)

func file_proto_precrux_precrux_proto_rawDescGZIP() []byte {
	file_proto_precrux_precrux_proto_rawDescOnce.Do(func() {
		file_proto_precrux_precrux_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_precrux_precrux_proto_rawDescData)
	})
	return file_proto_precrux_precrux_proto_rawDescData
}

var file_proto_precrux_precrux_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_precrux_precrux_proto_goTypes = []interface{}{
	(*PrecruxRequest)(nil),           // 0: chillyvee.precrux.PrecruxRequest
	(*PrecruxResponse)(nil),          // 1: chillyvee.precrux.PrecruxResponse
	(*PrecruxWriteFileRequest)(nil),  // 2: chillyvee.precrux.PrecruxWriteFileRequest
	(*PrecruxWriteFileResponse)(nil), // 3: chillyvee.precrux.PrecruxWriteFileResponse
}
var file_proto_precrux_precrux_proto_depIdxs = []int32{
	0, // 0: chillyvee.precrux.Precrux.UnaryPrecrux:input_type -> chillyvee.precrux.PrecruxRequest
	2, // 1: chillyvee.precrux.Precrux.WriteFile:input_type -> chillyvee.precrux.PrecruxWriteFileRequest
	1, // 2: chillyvee.precrux.Precrux.UnaryPrecrux:output_type -> chillyvee.precrux.PrecruxResponse
	3, // 3: chillyvee.precrux.Precrux.WriteFile:output_type -> chillyvee.precrux.PrecruxWriteFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_precrux_precrux_proto_init() }
func file_proto_precrux_precrux_proto_init() {
	if File_proto_precrux_precrux_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_precrux_precrux_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecruxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_precrux_precrux_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecruxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_precrux_precrux_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecruxWriteFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_precrux_precrux_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecruxWriteFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_precrux_precrux_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_precrux_precrux_proto_goTypes,
		DependencyIndexes: file_proto_precrux_precrux_proto_depIdxs,
		MessageInfos:      file_proto_precrux_precrux_proto_msgTypes,
	}.Build()
	File_proto_precrux_precrux_proto = out.File
	file_proto_precrux_precrux_proto_rawDesc = nil
	file_proto_precrux_precrux_proto_goTypes = nil
	file_proto_precrux_precrux_proto_depIdxs = nil
}
